# Generated by Django 3.2.19 on 2023-06-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=254)),
                ('body_part', models.BooleanField(default=False)),
            ],
        ),
    ]
