# Generated by Django 3.2.19 on 2023-06-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230618_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital_copy_price',
            field=models.DecimalField(decimal_places=2, default='0,00', max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Black and white drawing', 'Black and white drawing'), ('Colourful drawing', 'Colourful drawing'), ('Painting', 'Painting')], default='0,00', max_length=40),
        ),
    ]
