# Generated by Django 3.2.19 on 2023-06-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230618_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Black and white drawing', 'Black and white drawing'), ('Colourful drawing', 'Colourful drawing'), ('Painting', 'Painting')], default='Black and white drawing', max_length=40),
        ),
    ]
