# Generated by Django 3.2.19 on 2023-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230618_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital_copy_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
        ),
    ]
