# Generated by Django 3.2.19 on 2023-06-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20230618_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital_copy_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
